version: '3.7'
services:
    postgres:
        build: ./postgres_db/
        image: postgres:latest
        restart: always
        ports:
          - 5432:5432
        environment:
        - POSTGRES_USER=${DBUSER}
        - POSTGRES_PASSWORD=${DBPASSWORD}
        - POSTGRES_DB=${DB}
        logging:
          options:
            max-size: 10m
            max-file: "3"
        volumes: 
          - ./postgres-data:/var/lib/postgresql/data
    python-app:
        build: ./reddit_posts/